# # https://golangci-lint.run/usage/configuration#config-file
# issues:
#   exclude-use-default: true
#   exclude-case-sensitive: false
#   max-issues-per-linter: 50
#   max-same-issues: 3
#   new: false

# linters:
#   enable-all: false
#   disable-all: false
#   fast: false

# linters-settings:
#   {}

# output:
#   print-issued-lines: true
#   print-linter-name: true
#   unique-by-line: true
#   path-prefix: ""

# run:
#   timeout: "1m"
#   issue-exit-code: 1
#   tests: true
#   skip-dirs-use-default: true
#   allow-parallel-runners: false
#   go: "1.19"

# severity:
#   default-severity: error
#   case-sensitive: false