# https://golangci-lint.run/usage/configuration#config-file
issues:
  exclude-use-default: true
  exclude-case-sensitive: false
  max-issues-per-linter: 500
  max-same-issues: 30
  new: false

linters:
  fast: true
  enable-all: true
  disable:
    - deadcode
    - exhaustivestruct
    - golint
    - ifshort
    - interfacer
    - maligned
    - nosnakecase
    - scopelint
    - structcheck
    - varcheck

linters-settings:
  gci:
    custom-order: true
    sections:
      - standard
      - default
      - blank
      - dot
      - prefix(go.onebrick.io)

output:
  print-issued-lines: true
  print-linter-name: true
  unique-by-line: true
  path-prefix: ""

run:
  timeout: "1m"
  issue-exit-code: 1
  tests: true
  skip-dirs-use-default: true
  allow-parallel-runners: true
  go: "1.19"

severity:
  default-severity: warn
  case-sensitive: false
